name: Continuous Deployment

on: [push, pull_request]

jobs:
  cd:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test
        run: |
          ./run-test.sh
        env:
          CI: true
          SAXON_HOME: $GITHUB_WORKSPACE/elife-jats-schematron/validator
      - name: Publish as 'unstable'
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build --no-cache -t $DOCKER_USERNAME/$REPO_NAME:unstable .
          docker push $DOCKER_USERNAME/$REPO_NAME:unstable
          .scripts/github/retag-and-push.sh $REPO_NAME unstable
        env:
          REPO_NAME: basex-validator
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish as 'stable'
        if: contains(github.ref, 'refs/tags/v')
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build --no-cache -t $DOCKER_USERNAME/$REPO_NAME:stable .
          docker push $DOCKER_USERNAME/$REPO_NAME:stable
          .scripts/github/retag-and-push.sh $REPO_NAME stable
        env:
          REPO_NAME: basex-validator
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
